version: '3.8'

services:
  labmatcher-app:
    build: .
    ports:
      - "127.0.0.1:8080:8001"
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    env_file:
      - .env
    networks:
      - labmatcher-network
    restart: unless-stopped

networks:
  labmatcher-network:
    driver: bridge 